services:
  postgres:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_DB: TRUSTALERTDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - trustalert-network

  interface:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    environment:
      DBHOST: postgres
      POSTGRES_DB: TRUSTALERTDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - storage-volume:/app/storage
      - ./models:/app/models
    networks:
      - trustalert-network
    ports:
      - "3000:3000"

  download-server:
    build:
      context: ./download_server
      dockerfile: Dockerfile
    restart: always
    volumes:
      - storage-volume:/app/storage
    networks:
      - trustalert-network

volumes:
  storage-volume:

networks:
  trustalert-network:
    driver: bridge
